# Generated by Django 5.0.3 on 2024-03-10 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=255)),
                ('data_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_redact', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
