# Generated by Django 5.0.3 on 2024-03-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_note_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data_redact',
            field=models.DateTimeField(default='Не редактировался'),
        ),
    ]
