# Generated by Django 5.0.3 on 2024-03-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_note_data_redact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data_redact',
            field=models.DateTimeField(null=True),
        ),
    ]
